/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iptv_aidl_ALIAudioModeService */

#ifndef _Included_com_iptv_aidl_ALIAudioModeService
#define _Included_com_iptv_aidl_ALIAudioModeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iptv_aidl_ALIAudioModeService
 * Method:    jnigetAudioMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iptv_aidl_ALIAudioModeService_jnigetAudioMode
  (JNIEnv *, jobject);

/*
 * Class:     com_iptv_aidl_ALIAudioModeService
 * Method:    jnisetAudioMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iptv_aidl_ALIAudioModeService_jnisetAudioMode
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
