/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iptv_ipv6settings_Ipv6SettingActivity */

#ifndef _Included_com_iptv_ipv6settings_Ipv6SettingActivity
#define _Included_com_iptv_ipv6settings_Ipv6SettingActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_ipaddr
#define com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_ipaddr 0L
#undef com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_netmask
#define com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_netmask 1L
#undef com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_gateway
#define com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_gateway 2L
#undef com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_dns
#define com_iptv_ipv6settings_Ipv6SettingActivity_Info_ipv6_dns 3L
#undef com_iptv_ipv6settings_Ipv6SettingActivity_NUM_OF_Ipv6_Info
#define com_iptv_ipv6settings_Ipv6SettingActivity_NUM_OF_Ipv6_Info 4L
/*
 * Class:     com_iptv_ipv6settings_Ipv6SettingActivity
 * Method:    SetIpv6Add
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_iptv_ipv6settings_Ipv6SettingActivity_SetIpv6Add
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
