/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iptv_ipv6settings_Ipv6SettingActivity_ManualScene */

#ifndef _Included_com_iptv_ipv6settings_Ipv6SettingActivity_ManualScene
#define _Included_com_iptv_ipv6settings_Ipv6SettingActivity_ManualScene
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
